### ISSUE TITLE
Add configuration option for allowed ip to upload menus in api

### ISSUE THREAD

**Issue by WhySoBad** [virtbad/menu-api#2]
# Goal

At the moment it isn't possible for the menu-scraper to upload menus to the api when deployed in docker since uploads are only allowed from localhost. The scraper is run in another docker container and has therefore an unique ip.

It should be possible to set an environment variable with a hostname/ip from where the upload of menus is allowed. The default value should be localhost but in a docker deployment it could be set to the hostname of the menu-scraper container which would allow the upload to succeed.

* [ ] Add configuration option `menu.upload.ip` which defaults to `127.0.0.1`
* [ ] Rename the `NotLocalHost` exception to `NotConfiguredIp`
* [ ] Update docs to document how the upload ip can be set

**Comment by VirtCode** [comment]
Using regex instead of a list to allow for more flexibility. Using dns to resolve hostnames is sadly out of the scope of this project.
